/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexDothtmlRouteImport } from './routes/index[.]html'
import { Route as HomeReactPreviewRouteImport } from './routes/home-react-preview'
import { Route as IndexRouteImport } from './routes/index'

const IndexDothtmlRoute = IndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeReactPreviewRoute = HomeReactPreviewRouteImport.update({
  id: '/home-react-preview',
  path: '/home-react-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home-react-preview': typeof HomeReactPreviewRoute
  '/index.html': typeof IndexDothtmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home-react-preview': typeof HomeReactPreviewRoute
  '/index.html': typeof IndexDothtmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home-react-preview': typeof HomeReactPreviewRoute
  '/index.html': typeof IndexDothtmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home-react-preview' | '/index.html'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home-react-preview' | '/index.html'
  id: '__root__' | '/' | '/home-react-preview' | '/index.html'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeReactPreviewRoute: typeof HomeReactPreviewRoute
  IndexDothtmlRoute: typeof IndexDothtmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index.html': {
      id: '/index.html'
      path: '/index.html'
      fullPath: '/index.html'
      preLoaderRoute: typeof IndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-react-preview': {
      id: '/home-react-preview'
      path: '/home-react-preview'
      fullPath: '/home-react-preview'
      preLoaderRoute: typeof HomeReactPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeReactPreviewRoute: HomeReactPreviewRoute,
  IndexDothtmlRoute: IndexDothtmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
